defaults:
  - _self_

seed: 42
device: cpu
simulation: example

alignment:
  type: 'Linear'
  n_clusters: 24
  n_proto: 1000
  lmb: 0
  weighted: null
  
datamodule:
  dataset: cifar10
  train_label_size: 4200
  method: random
  grouping: label
  workers: 0
  batch_size: 512

channel:
  snr_db: null

models:
  transmitter: vit_small_patch16_224
  receiver: vit_base_patch16_224

sim:
  layers: 1
  meta_atoms_input_x: 16
  meta_atoms_input_y: 12
  meta_atoms_output_x: 24
  meta_atoms_output_y: 16
  meta_atoms_intermediate_x: 2
  meta_atoms_intermediate_y: 2
  wavelength: 0.005
  thickness_multiplier: 5
  thickness: ${eval:"${sim.thickness_multiplier} * ${sim.wavelength} * ${sim.layers}"}
  max_iters: 500
  lr: 1e-1
  decay: 0.8
  spacing_divisor_input: 2.0
  spacing_divisor_output: 2.0
  spacing_divisor_intermediate: 2.0
  meta_atom_spacing_input_x: ${eval:"${sim.wavelength} / ${sim.spacing_divisor_input}"}
  meta_atom_spacing_input_y: ${eval:"${sim.wavelength} / ${sim.spacing_divisor_input}"}
  meta_atom_spacing_output_x: ${eval:"${sim.wavelength} / ${sim.spacing_divisor_output}"}
  meta_atom_spacing_output_y: ${eval:"${sim.wavelength} / ${sim.spacing_divisor_output}"}
  meta_atom_spacing_intermediate_x: ${eval:"${sim.wavelength} / ${sim.spacing_divisor_intermediate}"}
  meta_atom_spacing_intermediate_y: ${eval:"${sim.wavelength} / ${sim.spacing_divisor_intermediate}"}
  
wandb:
  project: semantic_alignment_via_sim
